# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, ... }:

{
  imports = [ /mnt/nixos/common/hardware-configuration.nix ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ehci_pci" "ahci" "sd_mod" "sr_mod" "rtsx_pci_sdmmc" ];
  boot.kernelModules = [ "kvm-intel" ];

  fileSystems."/" =
    {
      device = "zroot/system/root";
      fsType = "zfs";
    };

  fileSystems."/boot" =
    {
      device = "/dev/disk/by-uuid/F213-C8D3";
      fsType = "vfat";
      options = ["noatime"];
    };

  fileSystems."/home/miminar" =
    {
      device = "zroot/user/miminar";
      fsType = "zfs";
    };

  fileSystems."/mnt/nixos" =
    {
      device = "zroot/system/nixos";
      fsType = "zfs";
    };

  fileSystems."/tmp" =
    {
      device = "zroot/local/tmp";
      fsType = "zfs";
    };

  swapDevices =
    [
      { device = "/dev/disk/by-uuid/0e411e96-7036-46c5-9802-206e84ced3d0"; }
    ];

  nix.maxJobs = lib.mkDefault 4;

  hardware = {
    pulseaudio.enable = true;
    trackpoint.enable = true;
  };
}
