# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, ... }:

{
  imports = [ ];

  boot.initrd.availableKernelModules = [ "ata_piix" "ohci_pci" "sd_mod" "sr_mod" ];
  boot.kernelModules = [ ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/9e1c7e44-cf39-4170-9344-a3f5fd8bed8a";
      fsType = "ext4";
      options = ["relatime" "discard"];
    };

  fileSystems."/home" =
    { device = "tank/home";
      fsType = "zfs";
      options = ["relatime"];
    };

  fileSystems."/nix" =
    { device = "tank/nixosmounter-nixroot";
      fsType = "zfs";
      options = ["noatime"];
    };

  fileSystems."/mnt/minap50root" =
    { device = "/dev/disk/by-uuid/9622f4c4-5ec6-4932-829f-f99ebaac05b7";
      fsType = "ext4";
      options = ["relatime" "discard"];
    };

  fileSystems."/var/lib/docker" =
    { device = "/dev/disk/by-uuid/3221df49-60e6-4c79-ab19-f3ea6f5668c6";
      fsType = "xfs";
      options = [ "noatime" "discard" ];
    };

  swapDevices = [ ];

  nix.maxJobs = lib.mkDefault 1;
  virtualisation.virtualbox.guest = {
    enable = true;
    x11 = false;
  };
}
