# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, ... }:

{
  imports = [ ];

  boot.initrd.availableKernelModules = [ "ata_piix" "ohci_pci" "sd_mod" "sr_mod" ];
  boot.kernelModules = [ ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/9e1c7e44-cf39-4170-9344-a3f5fd8bed8a";
      fsType = "ext4";
      options = ["relatime" "discard"];
    };

  fileSystems."/nix" =
    { device = "tank/mounter/nix";
      fsType = "zfs";
      options = ["relatime"];
    };

  fileSystems."/mnt/nixos" =
    { device = "enctank/nixos";
      fsType = "zfs";
      options = ["relatime"];
    };

  fileSystems."/home" =
    { device = "enctank/home";
      fsType = "zfs";
      options = ["relatime"];
    };

  fileSystems."/var/lib/docker" =
    { device = "/dev/disk/by-uuid/3bb39c50-c8f4-4355-bc5a-c836c12de945";
      fsType = "xfs";
      options = [ "noatime" "discard" ];
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/602391ae-1e7d-4ef1-9c40-4a30fb85ccfd"; }
    ];

  nix.maxJobs = lib.mkDefault 5;
  virtualisation.virtualbox.guest = {
    enable = true;
    x11    = true;
  };
}
