# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, ... }:

{
  imports = [
    <nixpkgs/nixos/modules/installer/scan/not-detected.nix>
    ./bind-mounts.nix
  ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "nvme" "usb_storage" "sr_mod" "sdhci_pci" "battery" ];
  boot.initrd.kernelModules = [];
  boot.kernelModules = [ "kvm-intel" "wacom" ];
  boot.extraModulePackages = [];

  fileSystems."/" =
    {
      device = "zroot/system/root";
      fsType = "zfs";
    };

  fileSystems."/tmp" =
    {
      device = "zroot/local/tmp";
      fsType = "zfs";
    };

  fileSystems."/nix" =
    {
      device = "zroot/local/nix";
      fsType = "zfs";
    };

  fileSystems."/mnt/nixos" =
    {
      device = "zroot/system/nixos";
      fsType = "zfs";
    };

  fileSystems."/home/miminar" =
    {
      device = "zdata/user/miminar";
      fsType = "zfs";
    };

  fileSystems."/root" =
    {
      device = "zdata/user/root";
      fsType = "zfs";
    };

  fileSystems."/boot" =
    {
      device = "/dev/disk/by-uuid/B5D3-DDEB";
      fsType = "vfat";
    };

  fileSystems."/home" =
    {
      device = "zdata/user/home";
      fsType = "zfs";
    };

  swapDevices =
    [
      { device = "/dev/disk/by-uuid/e55550b7-d15e-437d-8f2b-133af45681a3"; }
    ];

  nix.maxJobs = lib.mkDefault 12;
  powerManagement.cpuFreqGovernor = lib.mkDefault "powersave";

  hardware = {
    opengl = {
      driSupport32Bit = true;
      enable = true;
      extraPackages = with pkgs; [
        intel-media-driver # LIBVA_DRIVER_NAME=iHD
        vaapiIntel # LIBVA_DRIVER_NAME=i965 (older but works better for Firefox/Chromium)
        vaapiVdpau
        libvdpau-va-gl
      ];
    };
    trackpoint.enable = true;
    bluetooth = {
      enable = true;
      package = pkgs.bluezFull;
      powerOnBoot = false;
    };
    pulseaudio.enable = true;
    openrazer.enable = true;
  };
}
