# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, ... }:

{
  imports =
    [ <nixpkgs/nixos/modules/installer/scan/not-detected.nix>
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "nvme" "usb_storage" "sd_mod" "sr_mod" "rtsx_pci_sdmmc" ];
  boot.kernelModules = [ "kvm-intel" ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/9622f4c4-5ec6-4932-829f-f99ebaac05b7";
      fsType = "ext4";
      options = [ "relatime" "discard" ];
    };

#  fileSystems."/home" =
#    { device = "tank/home";
#      fsType = "zfs";
#      options = [ "relatime" ];
#    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/a458bf32-f408-484b-8aba-5c01d6cdfc42";
      fsType = "ext4";
      options = [ "noatime" "discard" ];
    };


  fileSystems."/boot/EFI" =
    { device = "/dev/disk/by-uuid/E656-19E3";
      fsType = "vfat";
      options = [ "noatime" "discard" ];
    };

  fileSystems."/var/lib/docker" =
    { device = "/dev/disk/by-uuid/3221df49-60e6-4c79-ab19-f3ea6f5668c6";
      fsType = "xfs";
      options = [ "noatime" "discard" ];
    };

  swapDevices = [ ];

  nix.maxJobs = lib.mkDefault 8;
  powerManagement.cpuFreqGovernor = "powersave";

  hardware = {
    # TODO: reenable
    opengl.driSupport32Bit = true;
    # TODO: make this work - turn hybrid graphis in BIOS on
    bumblebee = {
      enable = false;
      connectDisplay = false;
    };
    pulseaudio = {
      enable = true;
      support32Bit = true;
    };
    bluetooth = {
      enable = true;
      powerOnBoot = false;
    };
  };

}
