# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [
      (modulesPath + "/profiles/qemu-guest.nix")
    ];

  boot.initrd.availableKernelModules = [ "ata_piix" "uhci_hcd" "virtio_pci" "sr_mod" "virtio_blk" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    {
      device = "zroot/system/root";
      fsType = "zfs";
      options = [ "zfsutil" ];
    };

  fileSystems."/boot" =
    {
      device = "/dev/vda1";
      fsType = "xfs";
      options = [ "noatime" ];
    };

  fileSystems."/nix" =
    {
      device = "zroot/local/nix";
      fsType = "zfs";
      ## due to mountpoint=legacy
      # options = [ "zfsutil" ];
    };

  swapDevices =
    [{
      device = "/dev/disk/by-path/pci-0000:00:05.0-part2";
      randomEncryption.enable = true;
    }];

  networking.useDHCP = false;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
}
