# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, ... }:

{
  imports =
    [
      <nixpkgs/nixos/modules/installer/scan/not-detected.nix>
    ];

  boot.kernelModules = lib.mkAfter [
    "i2c-dev" # to control monitor brightness
  ];
  boot.extraModulePackages = lib.mkAfter [ config.boot.kernelPackages.exfat-nofuse ];

  powerManagement.cpuFreqGovernor = lib.mkDefault "powersave";
}

# ex: set et ts=2 sw=2 :
