# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, ... }:

{
  imports = [ ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "sd_mod" "sr_mod" ];
  boot.kernelModules = [ ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/9e1c7e44-cf39-4170-9344-a3f5fd8bed8a";
      fsType = "ext4";
    };

  fileSystems."/nix" =
    { device = "tank/mounter/nix";
      fsType = "zfs";
      options = ["relatime"];
    };

  fileSystems."/home" =
    { device = "enctank/home";
      fsType = "zfs";
      options = ["relatime"];
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/602391ae-1e7d-4ef1-9c40-4a30fb85ccfd"; }
    ];

  nix.maxJobs = lib.mkDefault 5;
  virtualisation.virtualbox.guest.enable = true;
}
